# Use a slim OpenJDK base image
FROM openjdk:21-jdk-slim

# Copy the Spring Boot application jar to the container
COPY build/libs/demo-0.0.1-SNAPSHOT.jar /app.jar

# Expose the port for gRPC communication
EXPOSE 8080 9090

# Run the application
ENTRYPOINT ["java", "-jar", "/app.jar"]
